[drives.root]
builder = "docker"
dockerfile = "./build/Dockerfile.rootfs"
format = "ext2"

[drives.data]
builder = "empty"
user = "dapp"
size = "100Mb" # size can be given as string, or as a number in bytes