name: local_node
x-env: &env
  CARTESI_LOG_LEVEL: info
  CARTESI_AUTH_KIND: "mnemonic_file"
  CARTESI_BLOCKCHAIN_ID: ${CARTESI_BLOCKCHAIN_ID}
  CARTESI_AUTH_MNEMONIC_FILE: /run/secrets/mnemonic
  CARTESI_SNAPSHOTS_DIR: /var/lib/cartesi-rollups-node/snapshots
  CARTESI_BLOCKCHAIN_WS_ENDPOINT: ${CARTESI_BLOCKCHAIN_WS_ENDPOINT}
  CARTESI_BLOCKCHAIN_HTTP_ENDPOINT: ${CARTESI_BLOCKCHAIN_HTTP_ENDPOINT}
  CARTESI_CONTRACTS_INPUT_BOX_ADDRESS: ${CARTESI_CONTRACTS_INPUT_BOX_ADDRESS}
  CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS: ${CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS}
  CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS: ${CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS}
  CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS: ${CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS}
  CARTESI_DATABASE_CONNECTION: ${CARTESI_DATABASE_CONNECTION}

secrets:
  mnemonic:
    file: ./secrets/mnemonic

services:
  # PostgreSQL database for Cartesi state
  database:
    image: cartesi/rollups-database:0.12.0-alpha.20
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - default
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres || exit 1
      timeout: 1s
      interval: 10s
      retries: 5
      start_period: 10s
      start_interval: 200ms

  # Reads blockchain events
  evmreader:
    image: cartesi/rollups-runtime:0.12.0-alpha.20
    command: cartesi-rollups-evm-reader
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "10001:10001"
    environment:
      <<: *env

  # Processes inputs and manages state
  advancer:
    image: cartesi/rollups-runtime:0.12.0-alpha.20
    command: cartesi-rollups-advancer
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - node_data:/var/lib/cartesi-rollups-node/data
      - .cartesi:/var/lib/cartesi-rollups-node/snapshots
    networks:
      - default
    ports:
      - "10002:10002"
      - "10012:10012"
    environment:
      <<: *env

  # Validates rollups state and consensus
  validator:
    image: cartesi/rollups-runtime:0.12.0-alpha.20
    command: cartesi-rollups-validator
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "10003:10003"
    environment:
      <<: *env

  # Handles financial operations and rewards
  claimer:
    image: cartesi/rollups-runtime:0.12.0-alpha.20
    command: cartesi-rollups-claimer
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "10004:10004"
    environment:
      <<: *env
    secrets:
      - mnemonic

  # JSON-RPC API for frontend interaction
  jsonrpc-api:
    image: cartesi/rollups-runtime:0.12.0-alpha.20
    command: cartesi-rollups-jsonrpc-api
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "10005:10005"
      - "10011:10011"
    environment:
      <<: *env

  # Development mode - interactive shell
  dev-node:
    build:
      context: .
      dockerfile: build/Dockerfile.node
    stdin_open: true
    tty: true
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "10002:10002"
      - "10012:10012"
      - "10011:10011"
    volumes:
      - .cartesi:/var/lib/cartesi-rollups-node/snapshots
    environment:
      <<: *env
    command: /bin/bash

# Persistent storage for rollups data
volumes:
  node_data: