#
# Rollup
#

[rollup.TRIBES_DATABASE_CONNECTION]
go-type = "URL"
default = "sqlite:///mnt/data/tribes.db"
description = """Database connection string"""
used-by = ["rollup"]

[rollup.TRIBES_MAX_STARTUP_TIME]
go-type = "Duration"
default = "15"
description = """Maximum startup time for the rollup service"""
used-by = ["rollup"]


#
# Contracts
#

[contracts.TRIBES_ADMIN_ADDRESS]
go-type = "Address"
default = "0xD554153658E8D466428Fa48487f5aba18dF5E628"
description = """Address of the admin user"""

[contracts.TRIBES_ADMIN_ADDRESS_TEST]
go-type = "Address"
default = "0x976EA74026E726554dB657fA54763abd0C3a0aa9"
description = """Address of the admin user"""

[contracts.TRIBES_VERIFIER_ADDRESS]
go-type = "Address"
default = "0xc2D8eb4a934AEc7268E414a3Fa3D20E0572d714b"
description = """Address of the verifier contract, who can verify the social accounts"""

[contracts.TRIBES_VERIFIER_ADDRESS_TEST]
go-type = "Address"
default = "0x0000000000000000000000000000000000000025"
description = """Address of the verifier contract, who can verify the social accounts"""

[contracts.TRIBES_BADGE_FACTORY_ADDRESS]
go-type = "Address"
default = "0x85805ACaf14BAb97b8C6B3A28Ea001e28D9f2554"
description = """Address of the badge factory contract, who can deploy the badges"""

[contracts.TRIBES_EMERGENCY_WITHDRAW_ADDRESS]
go-type = "Address"
default = "0x1EcbED5bFfC231C0eb3E01AF5945fFf902E2D8De"
description = """Address of the emergency withdraw address"""

[contracts.TRIBES_SAFE_ERC721_MINT_ADDRESS]
go-type = "Address"
default = "0x287503047cFd7Ca9F2F7dFdf354E09c2b59C1625"
description = """Address of the safe ERC721 mint address"""
