# fly.toml app configuration file generated for cartesi-rollups-node on 2025-07-23T02:10:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cartesi-rollups-node'
primary_region = 'ams'

[build]
  dockerfile = 'build/Dockerfile.node'

[env]
  CARTESI_ADVANCER_POLLING_INTERVAL = '3'
  CARTESI_BLOCKCHAIN_DEFAULT_BLOCK = 'latest'
  CARTESI_BLOCKCHAIN_ID = '11155111'
  CARTESI_CLAIMER_POLLING_INTERVAL = '3'
  CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS = '0xc7006f70875BaDe89032001262A846D3Ee160051'
  CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS = '0xC7003566dD09Aa0fC0Ce201aC2769aFAe3BF0051'
  CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = '0xc70074BDD26d8cF983Ca6A5b89b8db52D5850051'
  CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS = '0xc700285Ab555eeB5201BC00CFD4b2CC8DED90051'
  CARTESI_EVM_READER_RETRY_POLICY_MAX_DELAY = '3'
  CARTESI_EVM_READER_RETRY_POLICY_MAX_RETRIES = '3'
  CARTESI_FEATURE_CLAIM_SUBMISSION_ENABLED = 'false'
  CARTESI_FEATURE_INPUT_READER_ENABLED = 'true'
  CARTESI_FEATURE_MACHINE_HASH_CHECK_ENABLED = 'true'
  CARTESI_LOG_LEVEL = 'info'
  CARTESI_MAX_STARTUP_TIME = '15'
  CARTESI_SNAPSHOTS_DIR = '/var/lib/cartesi-rollups-node/snapshots'
  CARTESI_VALIDATOR_POLLING_INTERVAL = '3'

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[[metrics]]
  port = 9000
  path = '/metrics'
