[rollup.TRIBES_MAX_STARTUP_TIME]
go-type = "Duration"
default = "10"
description = """Maximum startup time for the rollup service"""
used-by = ["rollup"]


#
# Contracts
#

[contracts.TRIBES_ADMIN_ADDRESS]
go-type = "Address"
default = "0xD554153658E8D466428Fa48487f5aba18dF5E628"
description = """Address of the admin user"""
used-by = ["rollup"]

[contracts.TRIBES_ADMIN_ADDRESS_TEST]
go-type = "Address"
default = "0x976EA74026E726554dB657fA54763abd0C3a0aa9"
description = """Address of the admin user"""
used-by = ["rollup"]

[contracts.TRIBES_VERIFIER_ADDRESS]
go-type = "Address"
default = "0xc2D8eb4a934AEc7268E414a3Fa3D20E0572d714b"
description = """Address of the verifier contract, who can verify the social accounts"""
used-by = ["rollup"]

[contracts.TRIBES_VERIFIER_ADDRESS_TEST]
go-type = "Address"
default = "0x0000000000000000000000000000000000000025"
description = """Address of the verifier contract, who can verify the social accounts"""
used-by = ["rollup"]

[contracts.TRIBES_DEPLOYER_ADDRESS]
go-type = "Address"
default = "0x0000000000000000000000000000000000000013"
description = """Address of the deployer contract, who can deploy the contracts"""
used-by = ["rollup"]

[contracts.TRIBES_EMERGENCY_WITHDRAW_ADDRESS]
go-type = "Address"
default = "0x0000000000000000000000000000000000000006"
description = """Address of the emergency withdraw address"""
used-by = ["rollup"]


[contracts.TRIBES_EMERGENCY_WITHDRAW_ADDRESS_TEST]
go-type = "Address"
default = "0x0000000000000000000000000000000000000001"
description = """Address of the emergency withdraw address"""
used-by = ["rollup"]

