// Code generated by internal/config/generate.
// DO NOT EDIT.
//

package config

import (
	"fmt"

	"github.com/spf13/viper"
)

var ErrNotDefined = fmt.Errorf("variable not defined")

func init() {
	// Automatically bind environment variables.
	viper.AutomaticEnv()
}

const (
	TRIBES_AUTH_KIND                       = "TRIBES_AUTH_KIND"
	TRIBES_AUTH_MNEMONIC                   = "TRIBES_AUTH_MNEMONIC"
	TRIBES_AUTH_MNEMONIC_ACCOUNT_INDEX     = "TRIBES_AUTH_MNEMONIC_ACCOUNT_INDEX"
	TRIBES_AUTH_MNEMONIC_FILE              = "TRIBES_AUTH_MNEMONIC_FILE"
	TRIBES_AUTH_PRIVATE_KEY                = "TRIBES_AUTH_PRIVATE_KEY"
	TRIBES_AUTH_PRIVATE_KEY_FILE           = "TRIBES_AUTH_PRIVATE_KEY_FILE"
	TRIBES_BLOCKCHAIN_DEFAULT_BLOCK        = "TRIBES_BLOCKCHAIN_DEFAULT_BLOCK"
	TRIBES_BLOCKCHAIN_HTTP_ENDPOINT        = "TRIBES_BLOCKCHAIN_HTTP_ENDPOINT"
	TRIBES_BLOCKCHAIN_ID                   = "TRIBES_BLOCKCHAIN_ID"
	TRIBES_BLOCKCHAIN_LEGACY_ENABLED       = "TRIBES_BLOCKCHAIN_LEGACY_ENABLED"
	TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT = "TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT"
	TRIBES_BLOCKCHAIN_WS_ENDPOINT          = "TRIBES_BLOCKCHAIN_WS_ENDPOINT"
	TRIBES_CONTRACTS_APPLICATION_ADDRESS   = "TRIBES_CONTRACTS_APPLICATION_ADDRESS"
	TRIBES_CONTRACTS_ERC20_PORTAL_ADDRESS  = "TRIBES_CONTRACTS_ERC20_PORTAL_ADDRESS"
	TRIBES_CONTRACTS_INPUT_BOX_ADDRESS     = "TRIBES_CONTRACTS_INPUT_BOX_ADDRESS"
	TRIBES_LOG_COLOR                       = "TRIBES_LOG_COLOR"
	TRIBES_LOG_LEVEL                       = "TRIBES_LOG_LEVEL"
	TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES     = "TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES"
	TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT  = "TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT"
	TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT  = "TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT"
)

func SetDefaults() {
	// Set defaults based on the TOML definitions.

	viper.SetDefault(TRIBES_AUTH_KIND, "mnemonic")

	// no default for TRIBES_AUTH_MNEMONIC

	viper.SetDefault(TRIBES_AUTH_MNEMONIC_ACCOUNT_INDEX, "0")

	// no default for TRIBES_AUTH_MNEMONIC_FILE

	// no default for TRIBES_AUTH_PRIVATE_KEY

	// no default for TRIBES_AUTH_PRIVATE_KEY_FILE

	viper.SetDefault(TRIBES_BLOCKCHAIN_DEFAULT_BLOCK, "finalized")

	// no default for TRIBES_BLOCKCHAIN_HTTP_ENDPOINT

	// no default for TRIBES_BLOCKCHAIN_ID

	viper.SetDefault(TRIBES_BLOCKCHAIN_LEGACY_ENABLED, "false")

	viper.SetDefault(TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT, "60")

	// no default for TRIBES_BLOCKCHAIN_WS_ENDPOINT

	// no default for TRIBES_CONTRACTS_APPLICATION_ADDRESS

	viper.SetDefault(TRIBES_CONTRACTS_ERC20_PORTAL_ADDRESS, "0x05355c2F9bA566c06199DEb17212c3B78C1A3C31")

	viper.SetDefault(TRIBES_CONTRACTS_INPUT_BOX_ADDRESS, "0xB6b39Fb3dD926A9e3FBc7A129540eEbeA3016a6c")

	viper.SetDefault(TRIBES_LOG_COLOR, "true")

	viper.SetDefault(TRIBES_LOG_LEVEL, "info")

	viper.SetDefault(TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES, "4")

	viper.SetDefault(TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT, "60")

	viper.SetDefault(TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT, "1")

}

// McpConfig holds configuration values for the mcp service.
type McpConfig struct {

	// The default block to be used by EVM Reader and Claimer when requesting new blocks.
	// One of 'latest', 'pending', 'safe', 'finalized'
	TribesBlockchainDefaultBlock DefaultBlock `mapstructure:"TRIBES_BLOCKCHAIN_DEFAULT_BLOCK"`

	// HTTP endpoint for the blockchain RPC provider.
	TribesBlockchainHttpEndpoint URL `mapstructure:"TRIBES_BLOCKCHAIN_HTTP_ENDPOINT"`

	// An unique identifier representing a blockchain network.
	TribesBlockchainId uint64 `mapstructure:"TRIBES_BLOCKCHAIN_ID"`

	// If set to true the node will send transactions using the legacy gas fee model
	// (instead of EIP-1559).
	TribesBlockchainLegacyEnabled bool `mapstructure:"TRIBES_BLOCKCHAIN_LEGACY_ENABLED"`

	// Block subscription timeout in seconds.
	TribesBlockchainSubscriptionTimeout uint64 `mapstructure:"TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT"`

	// WebSocket endpoint for the blockchain RPC provider.
	TribesBlockchainWsEndpoint URL `mapstructure:"TRIBES_BLOCKCHAIN_WS_ENDPOINT"`

	// If set to true, the node will add colors to its log output.
	TribesLogColor bool `mapstructure:"TRIBES_LOG_COLOR"`

	// One of "debug", "info", "warn", "error".
	TribesLogLevel LogLevel `mapstructure:"TRIBES_LOG_LEVEL"`

	// Maximum number of retry attempts for HTTP blockchain requests after encountering an error.
	TribesBlockchainHttpMaxRetries uint64 `mapstructure:"TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES"`

	// Maximum wait time in seconds for the exponential backoff retry policy. The delay between retries for HTTP blockchain requests will never exceed this value, regardless of the backoff calculation.
	TribesBlockchainHttpRetryMaxWait Duration `mapstructure:"TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT"`

	// Minimum wait time in seconds for the exponential backoff retry policy. This is the initial delay before the first retry for HTTP blockchain requests.
	TribesBlockchainHttpRetryMinWait Duration `mapstructure:"TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT"`
}

// LoadMcpConfig reads configuration from environment variables, a config file, and defaults.
// Priority: command line flags > environment variables > config file > defaults.
func LoadMcpConfig() (*McpConfig, error) {
	SetDefaults()

	// Load config file if specified via --config flag.
	if cfgFile := viper.GetString("config"); cfgFile != "" {
		viper.SetConfigFile(cfgFile)
		if err := viper.ReadInConfig(); err != nil {
			return nil, fmt.Errorf("error reading config file: %w", err)
		}
	}

	var cfg McpConfig
	var err error

	cfg.TribesBlockchainDefaultBlock, err = GetTribesBlockchainDefaultBlock()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_DEFAULT_BLOCK: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_DEFAULT_BLOCK is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainHttpEndpoint, err = GetTribesBlockchainHttpEndpoint()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_HTTP_ENDPOINT: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_HTTP_ENDPOINT is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainId, err = GetTribesBlockchainId()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_ID: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_ID is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainLegacyEnabled, err = GetTribesBlockchainLegacyEnabled()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_LEGACY_ENABLED: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_LEGACY_ENABLED is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainSubscriptionTimeout, err = GetTribesBlockchainSubscriptionTimeout()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainWsEndpoint, err = GetTribesBlockchainWsEndpoint()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_WS_ENDPOINT: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_WS_ENDPOINT is required for the mcp service: %w", err)
	}

	cfg.TribesLogColor, err = GetTribesLogColor()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_LOG_COLOR: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_LOG_COLOR is required for the mcp service: %w", err)
	}

	cfg.TribesLogLevel, err = GetTribesLogLevel()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_LOG_LEVEL: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_LOG_LEVEL is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainHttpMaxRetries, err = GetTribesBlockchainHttpMaxRetries()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainHttpRetryMaxWait, err = GetTribesBlockchainHttpRetryMaxWait()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT is required for the mcp service: %w", err)
	}

	cfg.TribesBlockchainHttpRetryMinWait, err = GetTribesBlockchainHttpRetryMinWait()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT is required for the mcp service: %w", err)
	}

	return &cfg, nil
}

// GetTribesAuthKind returns the value for the environment variable TRIBES_AUTH_KIND.
func GetTribesAuthKind() (AuthKind, error) {
	s := viper.GetString(TRIBES_AUTH_KIND)
	if s != "" {
		v, err := toAuthKind(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_AUTH_KIND, err)
		}
		return v, nil
	}
	return notDefinedAuthKind(), fmt.Errorf("%s: %w", TRIBES_AUTH_KIND, ErrNotDefined)
}

// GetTribesAuthMnemonic returns the value for the environment variable TRIBES_AUTH_MNEMONIC.
func GetTribesAuthMnemonic() (RedactedString, error) {
	s := viper.GetString(TRIBES_AUTH_MNEMONIC)
	if s != "" {
		v, err := toRedactedString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_AUTH_MNEMONIC, err)
		}
		return v, nil
	}
	return notDefinedRedactedString(), fmt.Errorf("%s: %w", TRIBES_AUTH_MNEMONIC, ErrNotDefined)
}

// GetTribesAuthMnemonicAccountIndex returns the value for the environment variable TRIBES_AUTH_MNEMONIC_ACCOUNT_INDEX.
func GetTribesAuthMnemonicAccountIndex() (RedactedUint, error) {
	s := viper.GetString(TRIBES_AUTH_MNEMONIC_ACCOUNT_INDEX)
	if s != "" {
		v, err := toRedactedUint(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_AUTH_MNEMONIC_ACCOUNT_INDEX, err)
		}
		return v, nil
	}
	return notDefinedRedactedUint(), fmt.Errorf("%s: %w", TRIBES_AUTH_MNEMONIC_ACCOUNT_INDEX, ErrNotDefined)
}

// GetTribesAuthMnemonicFile returns the value for the environment variable TRIBES_AUTH_MNEMONIC_FILE.
func GetTribesAuthMnemonicFile() (string, error) {
	s := viper.GetString(TRIBES_AUTH_MNEMONIC_FILE)
	if s != "" {
		v, err := toString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_AUTH_MNEMONIC_FILE, err)
		}
		return v, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", TRIBES_AUTH_MNEMONIC_FILE, ErrNotDefined)
}

// GetTribesAuthPrivateKey returns the value for the environment variable TRIBES_AUTH_PRIVATE_KEY.
func GetTribesAuthPrivateKey() (RedactedString, error) {
	s := viper.GetString(TRIBES_AUTH_PRIVATE_KEY)
	if s != "" {
		v, err := toRedactedString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_AUTH_PRIVATE_KEY, err)
		}
		return v, nil
	}
	return notDefinedRedactedString(), fmt.Errorf("%s: %w", TRIBES_AUTH_PRIVATE_KEY, ErrNotDefined)
}

// GetTribesAuthPrivateKeyFile returns the value for the environment variable TRIBES_AUTH_PRIVATE_KEY_FILE.
func GetTribesAuthPrivateKeyFile() (string, error) {
	s := viper.GetString(TRIBES_AUTH_PRIVATE_KEY_FILE)
	if s != "" {
		v, err := toString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_AUTH_PRIVATE_KEY_FILE, err)
		}
		return v, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", TRIBES_AUTH_PRIVATE_KEY_FILE, ErrNotDefined)
}

// GetTribesBlockchainDefaultBlock returns the value for the environment variable TRIBES_BLOCKCHAIN_DEFAULT_BLOCK.
func GetTribesBlockchainDefaultBlock() (DefaultBlock, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_DEFAULT_BLOCK)
	if s != "" {
		v, err := toDefaultBlock(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_DEFAULT_BLOCK, err)
		}
		return v, nil
	}
	return notDefinedDefaultBlock(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_DEFAULT_BLOCK, ErrNotDefined)
}

// GetTribesBlockchainHttpEndpoint returns the value for the environment variable TRIBES_BLOCKCHAIN_HTTP_ENDPOINT.
func GetTribesBlockchainHttpEndpoint() (URL, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_HTTP_ENDPOINT)
	if s != "" {
		v, err := toURL(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_HTTP_ENDPOINT, err)
		}
		return v, nil
	}
	return notDefinedURL(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_HTTP_ENDPOINT, ErrNotDefined)
}

// GetTribesBlockchainId returns the value for the environment variable TRIBES_BLOCKCHAIN_ID.
func GetTribesBlockchainId() (uint64, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_ID)
	if s != "" {
		v, err := toUint64(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_ID, err)
		}
		return v, nil
	}
	return notDefineduint64(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_ID, ErrNotDefined)
}

// GetTribesBlockchainLegacyEnabled returns the value for the environment variable TRIBES_BLOCKCHAIN_LEGACY_ENABLED.
func GetTribesBlockchainLegacyEnabled() (bool, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_LEGACY_ENABLED)
	if s != "" {
		v, err := toBool(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_LEGACY_ENABLED, err)
		}
		return v, nil
	}
	return notDefinedbool(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_LEGACY_ENABLED, ErrNotDefined)
}

// GetTribesBlockchainSubscriptionTimeout returns the value for the environment variable TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT.
func GetTribesBlockchainSubscriptionTimeout() (uint64, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT)
	if s != "" {
		v, err := toUint64(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT, err)
		}
		return v, nil
	}
	return notDefineduint64(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_SUBSCRIPTION_TIMEOUT, ErrNotDefined)
}

// GetTribesBlockchainWsEndpoint returns the value for the environment variable TRIBES_BLOCKCHAIN_WS_ENDPOINT.
func GetTribesBlockchainWsEndpoint() (URL, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_WS_ENDPOINT)
	if s != "" {
		v, err := toURL(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_WS_ENDPOINT, err)
		}
		return v, nil
	}
	return notDefinedURL(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_WS_ENDPOINT, ErrNotDefined)
}

// GetTribesContractsApplicationAddress returns the value for the environment variable TRIBES_CONTRACTS_APPLICATION_ADDRESS.
func GetTribesContractsApplicationAddress() (Address, error) {
	s := viper.GetString(TRIBES_CONTRACTS_APPLICATION_ADDRESS)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_CONTRACTS_APPLICATION_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_CONTRACTS_APPLICATION_ADDRESS, ErrNotDefined)
}

// GetTribesContractsErc20PortalAddress returns the value for the environment variable TRIBES_CONTRACTS_ERC20_PORTAL_ADDRESS.
func GetTribesContractsErc20PortalAddress() (Address, error) {
	s := viper.GetString(TRIBES_CONTRACTS_ERC20_PORTAL_ADDRESS)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_CONTRACTS_ERC20_PORTAL_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_CONTRACTS_ERC20_PORTAL_ADDRESS, ErrNotDefined)
}

// GetTribesContractsInputBoxAddress returns the value for the environment variable TRIBES_CONTRACTS_INPUT_BOX_ADDRESS.
func GetTribesContractsInputBoxAddress() (Address, error) {
	s := viper.GetString(TRIBES_CONTRACTS_INPUT_BOX_ADDRESS)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_CONTRACTS_INPUT_BOX_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_CONTRACTS_INPUT_BOX_ADDRESS, ErrNotDefined)
}

// GetTribesLogColor returns the value for the environment variable TRIBES_LOG_COLOR.
func GetTribesLogColor() (bool, error) {
	s := viper.GetString(TRIBES_LOG_COLOR)
	if s != "" {
		v, err := toBool(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_LOG_COLOR, err)
		}
		return v, nil
	}
	return notDefinedbool(), fmt.Errorf("%s: %w", TRIBES_LOG_COLOR, ErrNotDefined)
}

// GetTribesLogLevel returns the value for the environment variable TRIBES_LOG_LEVEL.
func GetTribesLogLevel() (LogLevel, error) {
	s := viper.GetString(TRIBES_LOG_LEVEL)
	if s != "" {
		v, err := toLogLevel(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_LOG_LEVEL, err)
		}
		return v, nil
	}
	return notDefinedLogLevel(), fmt.Errorf("%s: %w", TRIBES_LOG_LEVEL, ErrNotDefined)
}

// GetTribesBlockchainHttpMaxRetries returns the value for the environment variable TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES.
func GetTribesBlockchainHttpMaxRetries() (uint64, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES)
	if s != "" {
		v, err := toUint64(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES, err)
		}
		return v, nil
	}
	return notDefineduint64(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_HTTP_MAX_RETRIES, ErrNotDefined)
}

// GetTribesBlockchainHttpRetryMaxWait returns the value for the environment variable TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT.
func GetTribesBlockchainHttpRetryMaxWait() (Duration, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT)
	if s != "" {
		v, err := toDuration(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT, err)
		}
		return v, nil
	}
	return notDefinedDuration(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_HTTP_RETRY_MAX_WAIT, ErrNotDefined)
}

// GetTribesBlockchainHttpRetryMinWait returns the value for the environment variable TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT.
func GetTribesBlockchainHttpRetryMinWait() (Duration, error) {
	s := viper.GetString(TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT)
	if s != "" {
		v, err := toDuration(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT, err)
		}
		return v, nil
	}
	return notDefinedDuration(), fmt.Errorf("%s: %w", TRIBES_BLOCKCHAIN_HTTP_RETRY_MIN_WAIT, ErrNotDefined)
}
