// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package root

import (
	"github.com/tribeshq/tribes/internal/infra/cartesi/handler/advance"
	"github.com/tribeshq/tribes/internal/infra/cartesi/handler/inspect"
	"github.com/tribeshq/tribes/internal/infra/repository"
)

// Injectors from wire.go:

func NewHandlers(repo repository.Repository) (*Handlers, error) {
	orderAdvanceHandlers := advance.NewOrderAdvanceHandlers(repo, repo, repo)
	userAdvanceHandlers := advance.NewUserAdvanceHandlers(repo)
	socialAccountAdvanceHandlers := advance.NewSocialAccountAdvanceHandlers(repo, repo)
	campaignAdvanceHandlers := advance.NewCampaignAdvanceHandlers(repo, repo, repo)
	orderInspectHandlers := inspect.NewOrderInspectHandlers(repo)
	userInspectHandlers := inspect.NewUserInspectHandlers(repo)
	socialAccountInspectHandlers := inspect.NewSocialAccountInspectHandlers(repo)
	campaignInspectHandlers := inspect.NewCampaignInspectHandlers(repo)
	handlers := &Handlers{
		OrderAdvanceHandlers:    orderAdvanceHandlers,
		UserAdvanceHandlers:     userAdvanceHandlers,
		SocialAccountsHandlers:  socialAccountAdvanceHandlers,
		CampaignAdvanceHandlers: campaignAdvanceHandlers,
		OrderInspectHandlers:    orderInspectHandlers,
		UserInspectHandlers:     userInspectHandlers,
		SocialAccountHandlers:   socialAccountInspectHandlers,
		CampaignInspectHandlers: campaignInspectHandlers,
	}
	return handlers, nil
}

// wire.go:

// Handlers contains all handler dependencies
type Handlers struct {
	// Advance handlers
	OrderAdvanceHandlers    *advance.OrderAdvanceHandlers
	UserAdvanceHandlers     *advance.UserAdvanceHandlers
	SocialAccountsHandlers  *advance.SocialAccountAdvanceHandlers
	CampaignAdvanceHandlers *advance.CampaignAdvanceHandlers

	// Inspect handlers
	OrderInspectHandlers    *inspect.OrderInspectHandlers
	UserInspectHandlers     *inspect.UserInspectHandlers
	SocialAccountHandlers   *inspect.SocialAccountInspectHandlers
	CampaignInspectHandlers *inspect.CampaignInspectHandlers
}
