// Code generated by internal/config/generate.
// DO NOT EDIT.
//
// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

package configs

import (
	"fmt"

	"github.com/spf13/viper"
)

var ErrNotDefined = fmt.Errorf("variable not defined")

func init() {
	// Automatically bind environment variables.
	viper.AutomaticEnv()
}

const (
	TRIBES_ADMIN_ADDRESS         = "TRIBES_ADMIN_ADDRESS"
	TRIBES_ADMIN_ADDRESS_TEST    = "TRIBES_ADMIN_ADDRESS_TEST"
	TRIBES_DEPLOYER_ADDRESS      = "TRIBES_DEPLOYER_ADDRESS"
	TRIBES_DEPLOYER_ADDRESS_TEST = "TRIBES_DEPLOYER_ADDRESS_TEST"
	TRIBES_VERIFIER_ADDRESS      = "TRIBES_VERIFIER_ADDRESS"
	TRIBES_VERIFIER_ADDRESS_TEST = "TRIBES_VERIFIER_ADDRESS_TEST"
)

func SetDefaults() {
	// Set defaults based on the TOML definitions.

	viper.SetDefault(TRIBES_ADMIN_ADDRESS, "0xD554153658E8D466428Fa48487f5aba18dF5E628")

	viper.SetDefault(TRIBES_ADMIN_ADDRESS_TEST, "0x976EA74026E726554dB657fA54763abd0C3a0aa9")

	viper.SetDefault(TRIBES_DEPLOYER_ADDRESS, "0x0000000000000000000000000000000000000006")

	viper.SetDefault(TRIBES_DEPLOYER_ADDRESS_TEST, "0x0000000000000000000000000000000000000024")

	viper.SetDefault(TRIBES_VERIFIER_ADDRESS, "0xc2D8eb4a934AEc7268E414a3Fa3D20E0572d714b")

	viper.SetDefault(TRIBES_VERIFIER_ADDRESS_TEST, "0x0000000000000000000000000000000000000025")

}

// RollupConfig holds configuration values for the rollup.
type RollupConfig struct {

	// Address of the admin user
	TribesAdminAddress Address `mapstructure:"TRIBES_ADMIN_ADDRESS"`

	// Address of the admin user
	TribesAdminAddressTest Address `mapstructure:"TRIBES_ADMIN_ADDRESS_TEST"`

	// Address of the deployer user, who can deploy the contracts
	TribesDeployerAddress Address `mapstructure:"TRIBES_DEPLOYER_ADDRESS"`

	// Address of the deployer user, who can deploy the contracts
	TribesDeployerAddressTest Address `mapstructure:"TRIBES_DEPLOYER_ADDRESS_TEST"`

	// Address of the verifier user, who can verify the social accounts
	TribesVerifierAddress Address `mapstructure:"TRIBES_VERIFIER_ADDRESS"`

	// Address of the verifier user, who can verify the social accounts
	TribesVerifierAddressTest Address `mapstructure:"TRIBES_VERIFIER_ADDRESS_TEST"`
}

// LoadRollupConfig reads configuration from environment variables, a config file, and defaults.
// Priority: command line flags > environment variables > config file > defaults.
func LoadRollupConfig() (*RollupConfig, error) {
	SetDefaults()

	// Load config file if specified via --config flag.
	if cfgFile := viper.GetString("config"); cfgFile != "" {
		viper.SetConfigFile(cfgFile)
		if err := viper.ReadInConfig(); err != nil {
			return nil, fmt.Errorf("error reading config file: %w", err)
		}
	}

	var cfg RollupConfig
	var err error

	cfg.TribesAdminAddress, err = GetTribesAdminAddress()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_ADMIN_ADDRESS: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_ADMIN_ADDRESS is required for the rollup service: %w", err)
	}

	cfg.TribesAdminAddressTest, err = GetTribesAdminAddressTest()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_ADMIN_ADDRESS_TEST: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_ADMIN_ADDRESS_TEST is required for the rollup service: %w", err)
	}

	cfg.TribesDeployerAddress, err = GetTribesDeployerAddress()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_DEPLOYER_ADDRESS: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_DEPLOYER_ADDRESS is required for the rollup service: %w", err)
	}

	cfg.TribesDeployerAddressTest, err = GetTribesDeployerAddressTest()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_DEPLOYER_ADDRESS_TEST: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_DEPLOYER_ADDRESS_TEST is required for the rollup service: %w", err)
	}

	cfg.TribesVerifierAddress, err = GetTribesVerifierAddress()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_VERIFIER_ADDRESS: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_VERIFIER_ADDRESS is required for the rollup service: %w", err)
	}

	cfg.TribesVerifierAddressTest, err = GetTribesVerifierAddressTest()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get TRIBES_VERIFIER_ADDRESS_TEST: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("TRIBES_VERIFIER_ADDRESS_TEST is required for the rollup service: %w", err)
	}

	return &cfg, nil
}

// GetTribesAdminAddress returns the value for the environment variable TRIBES_ADMIN_ADDRESS.
func GetTribesAdminAddress() (Address, error) {
	s := viper.GetString(TRIBES_ADMIN_ADDRESS)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_ADMIN_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_ADMIN_ADDRESS, ErrNotDefined)
}

// GetTribesAdminAddressTest returns the value for the environment variable TRIBES_ADMIN_ADDRESS_TEST.
func GetTribesAdminAddressTest() (Address, error) {
	s := viper.GetString(TRIBES_ADMIN_ADDRESS_TEST)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_ADMIN_ADDRESS_TEST, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_ADMIN_ADDRESS_TEST, ErrNotDefined)
}

// GetTribesDeployerAddress returns the value for the environment variable TRIBES_DEPLOYER_ADDRESS.
func GetTribesDeployerAddress() (Address, error) {
	s := viper.GetString(TRIBES_DEPLOYER_ADDRESS)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_DEPLOYER_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_DEPLOYER_ADDRESS, ErrNotDefined)
}

// GetTribesDeployerAddressTest returns the value for the environment variable TRIBES_DEPLOYER_ADDRESS_TEST.
func GetTribesDeployerAddressTest() (Address, error) {
	s := viper.GetString(TRIBES_DEPLOYER_ADDRESS_TEST)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_DEPLOYER_ADDRESS_TEST, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_DEPLOYER_ADDRESS_TEST, ErrNotDefined)
}

// GetTribesVerifierAddress returns the value for the environment variable TRIBES_VERIFIER_ADDRESS.
func GetTribesVerifierAddress() (Address, error) {
	s := viper.GetString(TRIBES_VERIFIER_ADDRESS)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_VERIFIER_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_VERIFIER_ADDRESS, ErrNotDefined)
}

// GetTribesVerifierAddressTest returns the value for the environment variable TRIBES_VERIFIER_ADDRESS_TEST.
func GetTribesVerifierAddressTest() (Address, error) {
	s := viper.GetString(TRIBES_VERIFIER_ADDRESS_TEST)
	if s != "" {
		v, err := toAddress(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TRIBES_VERIFIER_ADDRESS_TEST, err)
		}
		return v, nil
	}
	return notDefinedAddress(), fmt.Errorf("%s: %w", TRIBES_VERIFIER_ADDRESS_TEST, ErrNotDefined)
}
