name: release

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.1

      - name: Install Cartesi CLI
        run: npm install -g @cartesi/cli@2.0.0-alpha.15

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            contracts/node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('contracts/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install contracts dependencies
        run: |
          forge soldeer install
          pnpm install --frozen-lockfile
        working-directory: ./contracts

      - name: Run Solidity tests
        run: forge test -vvv --root ./contracts

      - name: Run Go tests
        run: go test -p=1 ./...

      - name: Log in to Container registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tribes Rollup initial snapshot
        run: |
          # Enable Docker BuildKit for better performance
          export DOCKER_BUILDKIT=1
          make build
        env:
          DOCKER_BUILDKIT: 1
          # Cache Docker layers
          BUILDKIT_INLINE_CACHE: 1

      - name: Create artifact archive for initial snapshot
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar -czf tribes-snapshot.tar.gz -C .cartesi/image .
          sha256sum tribes-snapshot.tar.gz > tribes-snapshot.tar.gz.sha256

      - name: Upload build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: tribes-snapshot
          path: |
            tribes-snapshot.tar.gz
            tribes-snapshot.tar.gz.sha256
          retention-days: 30

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -name "*.tar.gz" -exec cp {} release-assets/ \;
          find artifacts -name "*.sha256" -exec cp {} release-assets/ \;

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, '-rc') }}
          files: release-assets/*
          fail_on_unmatched_files: true